// <auto-generated />
using System;
using MTGApplication;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MTGApplication.Migrations
{
    [DbContext(typeof(Database.CardCollectionContext))]
    partial class CardCollectionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("MTGApplication.Database+Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScryfallId")
                        .HasColumnType("varchar(36)");

                    b.HasKey("CardId");

                    b.HasIndex("CardListId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("MTGApplication.Database+CardDeck", b =>
                {
                    b.Property<int>("CardDeckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CardlistId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaybelistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WishlistId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CardDeckId");

                    b.HasIndex("CardlistId")
                        .IsUnique();

                    b.HasIndex("MaybelistId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("WishlistId")
                        .IsUnique();

                    b.ToTable("CardDecks");
                });

            modelBuilder.Entity("MTGApplication.Database+ListOfCards", b =>
                {
                    b.Property<int>("ListOfCardsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("ListOfCardsId");

                    b.ToTable("ListsOfCards");
                });

            modelBuilder.Entity("MTGApplication.Database+Card", b =>
                {
                    b.HasOne("MTGApplication.Database+ListOfCards", "CardList")
                        .WithMany("Cards")
                        .HasForeignKey("CardListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardList");
                });

            modelBuilder.Entity("MTGApplication.Database+CardDeck", b =>
                {
                    b.HasOne("MTGApplication.Database+ListOfCards", "Cardlist")
                        .WithOne()
                        .HasForeignKey("MTGApplication.Database+CardDeck", "CardlistId");

                    b.HasOne("MTGApplication.Database+ListOfCards", "Maybelist")
                        .WithOne()
                        .HasForeignKey("MTGApplication.Database+CardDeck", "MaybelistId");

                    b.HasOne("MTGApplication.Database+ListOfCards", "Wishlist")
                        .WithOne()
                        .HasForeignKey("MTGApplication.Database+CardDeck", "WishlistId");

                    b.Navigation("Cardlist");

                    b.Navigation("Maybelist");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("MTGApplication.Database+ListOfCards", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
