// <auto-generated />
using System;
using MTGApplication.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MTGApplication.Database.Migrations
{
    [DbContext(typeof(CardDatabaseContext))]
    partial class CardDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("MTGApplication.Models.MTGCard", b =>
                {
                    b.Property<int>("MTGCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MTGCardDeckDeckCardsId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MTGCardDeckMaybelistId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MTGCardDeckWishlistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScryfallId")
                        .HasColumnType("varchar(36)");

                    b.HasKey("MTGCardId");

                    b.HasIndex("MTGCardDeckDeckCardsId");

                    b.HasIndex("MTGCardDeckMaybelistId");

                    b.HasIndex("MTGCardDeckWishlistId");

                    b.ToTable("MTGCards");
                });

            modelBuilder.Entity("MTGApplication.Models.MTGCardDeck", b =>
                {
                    b.Property<int>("MTGCardDeckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MTGCardDeckId");

                    b.ToTable("MTGCardDecks");
                });

            modelBuilder.Entity("MTGApplication.Models.MTGCard", b =>
                {
                    b.HasOne("MTGApplication.Models.MTGCardDeck", "MTGCardDeckDeckCards")
                        .WithMany("DeckCards")
                        .HasForeignKey("MTGCardDeckDeckCardsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MTGApplication.Models.MTGCardDeck", "MTGCardDeckMaybelist")
                        .WithMany("Maybelist")
                        .HasForeignKey("MTGCardDeckMaybelistId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MTGApplication.Models.MTGCardDeck", "MTGCardDeckWishlist")
                        .WithMany("Wishlist")
                        .HasForeignKey("MTGCardDeckWishlistId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MTGCardDeckDeckCards");

                    b.Navigation("MTGCardDeckMaybelist");

                    b.Navigation("MTGCardDeckWishlist");
                });

            modelBuilder.Entity("MTGApplication.Models.MTGCardDeck", b =>
                {
                    b.Navigation("DeckCards");

                    b.Navigation("Maybelist");

                    b.Navigation("Wishlist");
                });
#pragma warning restore 612, 618
        }
    }
}
